config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  get 'seguranca_trabalho/index', to: 'seguranca_trabalho#index', path: 'sesmt'
  match 'seguranca_trabalho/importar', to: 'seguranca_trabalho#importar', path: 'importar', via: [:get, :post]

  get 'servico/index', to: 'servico#index', path: 'servico'

  match 'seguranca_trabalho/relatorio_atestados', to: 'seguranca_trabalho#relatorio_atestados', path: 'sesmt/relatorio_atestados', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_cids', to: 'seguranca_trabalho#relatorio_cids', path: 'sesmt/relatorio_cids', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_abs', to: 'seguranca_trabalho#relatorio_abs', path: 'sesmt/relatorio_abs', via: [:get, :post]


  match 'seguranca_trabalho/faltas_legais_old', to: 'seguranca_trabalho#faltas_legais_old', path: 'sesmt/faltas_legais_old', via: [:get, :post]

  match 'servico/boleto', to: 'servico#boleto', path: 'servico/boleto', via: [:get, :post]

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/servico_controller.rb
#encoding: utf-8

class ServicoController < ApplicationController

  def index
  end

  def boleto
   @file_pdf = params[:file_pdf] || nil
   @file_excel = params[:file_excel] || nil
   p params
   if(params[:commit].present?)
     if(params[:file_pdf])
       @file_pdf = params[:file_pdf]
       @file_excel = params[:file_excel]

       @billet = Vikstar::Billet.new({file_pdf: @file_pdf, file_excel: @file_excel})
     else
       flash[:alert] = "Por favor, envie um arquivo do tipo PDF/Excel"
     end
   end
  end
end

app/views/servico/boleto.html.erb
<%= render partial: 'form', locals: { path: servico_boleto_path } %>
<div class="col-md-12 ">
	<div class="col-md-12  statistics">
	    <div class="col-md-2  statistics__container">
	        <div class="statistics__circle">
	           <p class="statistics__number qty-billet-pdf">00</p>
	            <p class="statistics__title">Quantidade</p>
	        </div>

	    </div>
	    <div class="col-md-2  statistics__container">
            <div class="statistics__circle">
                <p class="statistics__real">R$</p>
                <p class="statistics__number total-billet-pdf">00</p>
                <p class="statistics__title">Valor total</p>
            </div>
        </div>
        <div class="col-md-2  statistics__container">
            <div class="statistics__circle">
                <p class="statistics__real">R$</p>
                <p class="statistics__number total-difference">00</p>
                <p class="statistics__title">Valor da diferença</p>
            </div>
        </div>
        <div class="col-md-6 ">
          <div class="chart__container">

          </div>
        </div>
	</div>
	<div id="container" class="col-md-12 ">
	</div>
</div>

<script>

var result = {
	'billet': <%= raw @billet.to_json %>
}


console.log(result);
if(result['billet']){
	Billet.set(result['billet']);
	Billet.init();
}
</script>
<%- title "Análise" %>

app/views/servico/index.html.erb
<h1>Você quer resolver?</h1>
<div class="small-12 columns">
	<ul class="small-block-grid-6 menu-grid">
	  <li>
	  	<%= link_to servico_boleto_path do %>
            <div class="content">
                <p>Boleto Teletáxi</p>
            </div>
        <% end %>
	  </li>
	</ul>
</div>