config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  get 'seguranca_trabalho/index', to: 'seguranca_trabalho#index', path: 'sesmt'
  match 'seguranca_trabalho/importar', to: 'seguranca_trabalho#importar', path: 'importar', via: [:get, :post]

  get 'servico/index', to: 'servico#index', path: 'servico'

  match 'seguranca_trabalho/relatorio_atestados', to: 'seguranca_trabalho#relatorio_atestados', path: 'sesmt/relatorio_atestados', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_cids', to: 'seguranca_trabalho#relatorio_cids', path: 'sesmt/relatorio_cids', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_abs', to: 'seguranca_trabalho#relatorio_abs', path: 'sesmt/relatorio_abs', via: [:get, :post]


  match 'seguranca_trabalho/faltas_legais_old', to: 'seguranca_trabalho#faltas_legais_old', path: 'sesmt/faltas_legais_old', via: [:get, :post]

  match 'servico/boleto', to: 'servico#boleto', path: 'servico/boleto', via: [:get, :post]

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/home_controller.rb
#encoding: utf-8

class HomeController < ApplicationController

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Você quer ir para?</h3></div>
		<div class="panel-body">

			<div class="col-md-12 columns">
				<ul class="col-md-6 menu-grid">
				  <li class="workplace-safety">
				  	<%= link_to seguranca_trabalho_index_path do %>
			            <div class="content">
			                <p>SESMT</p>
			            </div>
			        <% end %>
				  </li>
			      <li class="service">
			      	<%= link_to servico_index_path do %>
			            <div class="content">
			                <p>Serviços</p>
			            </div>
			        <% end %>
			      </li>
				</ul>
			</div>
		</div>
	</div>