config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  get 'seguranca_trabalho/index', to: 'seguranca_trabalho#index', path: 'sesmt'
  match 'seguranca_trabalho/importar', to: 'seguranca_trabalho#importar', path: 'importar', via: [:get, :post]

  get 'servico/index', to: 'servico#index', path: 'servico'

  match 'seguranca_trabalho/relatorio_atestados', to: 'seguranca_trabalho#relatorio_atestados', path: 'sesmt/relatorio_atestados', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_cids', to: 'seguranca_trabalho#relatorio_cids', path: 'sesmt/relatorio_cids', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_abs', to: 'seguranca_trabalho#relatorio_abs', path: 'sesmt/relatorio_abs', via: [:get, :post]


  match 'seguranca_trabalho/faltas_legais_old', to: 'seguranca_trabalho#faltas_legais_old', path: 'sesmt/faltas_legais_old', via: [:get, :post]

  match 'servico/boleto', to: 'servico#boleto', path: 'servico/boleto', via: [:get, :post]

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/seguranca_trabalho_controller.rb
#encoding: utf-8

class SegurancaTrabalhoController < ApplicationController
  include Vikstar

  def index
  end

  def faltas_legais_old
    @file = params[:file] || nil
    if(params[:commit].present?)
      if(params[:file])
        @file = params[:file]
        @from = params[:from]
        @to = params[:to]

        @benchmark = {
          start: nil,
          finish: nil
        }
        @benchmark[:start] = Time.now
        @legal_faults = Vikstar::LegalFaults.new({file: @file, from: @from, to: @to})
        @benchmark[:finish] = Time.now

      else
        flash[:alert] = "Por favor, envie um arquivo do tipo Excel"
      end
    end
  end

  def relatorio_atestados
    if(params[:commit].present?)
      if(params[:daterange])
        @daterange = params[:daterange]
        periodo = params[:daterange].split(' - ')

        @from = DateTime.parse(periodo[0]).strftime('%Y-%m-%d')
        @to = DateTime.parse(periodo[1]).strftime('%Y-%m-%d')

        @benchmark = {
          start: nil,
          finish: nil
        }

        @benchmark[:start] = Time.now
        @atestados = AtestadoMedico.intervalo(@from,@to)
        @benchmark[:finish] = Time.now

      else
        flash[:alert] = "Por favor, envie um intervalo de datas válido"
      end
    end
  end

  def relatorio_abs
    if(params[:commit].present?)
      if(params[:ano])
        @ano = params[:ano]
        @atestado = AtestadoMedico
        @atestados_mensal_atestados = AtestadoMedico.abs_mensal_atestados(@ano)
        @atestados_mensal_area = AtestadoMedico.abs_mensal_area(@ano)
        @atestados_mensal_total_dias = AtestadoMedico.abs_mensal_total_dias(@ano).to_a

      else
        flash[:alert] = "Por favor, escolha um ano válido"
      end
    end
  end

  def importar
    @file = params[:file] || nil
    if(params[:commit].present?)
      if(params[:file])
        @file = params[:file]
        @legal_faults = {}
        @legal_faults = Vikstar::LegalFaultsImport.new({file: @file})
        @benchmark = {
          start: nil,
          finish: nil
        }
        @benchmark[:start] = Time.now
        @total_inserted = 0
        @total_errors = 0
        @legal_faults_registered = []
        @legal_faults_not_registered = []

        #measure('gc') do
        @legal_faults.data.each_with_index{ |a, i|
  				a.delete :id_aux
          a.delete :status

          atestado = AtestadoMedico.find_by(matricula: a[:matricula], cid: a[:cid], data_entrega: a[:data_entrega], data_atestado: a[:data_atestado])

          # atestado = AtestadoMedico.search(where: { matricula: a[:matricula], cid: a[:cid], data_entrega: a[:data_entrega], data_atestado: a[:data_atestado] } )

          if atestado.present?
            @legal_faults_registered << atestado
          else
            @legal_faults_not_registered << a
          end
  			}


        # too many terms in compound SELECT: INSERT INTO
        # inserts = []
        # @legal_faults_not_registered.each{ |atestado|
        #   inserts.push "(#{atestado[:filial]}, '#{atestado[:matricula]}', '#{atestado[:login]}', '#{atestado[:nome]}', '#{atestado[:tipo]}', '#{atestado[:cid]}', '#{atestado[:descricao]}', '#{atestado[:data_entrega]}', '#{atestado[:data_atestado]}', #{atestado[:qtd_dias]}, '#{atestado[:qtd_horas]}', '#{atestado[:data_retorno]}', '#{atestado[:incluido]}', '#{atestado[:data_cadastro]}', '#{atestado[:gerente]}', '#{atestado[:veracidade]}', '#{atestado[:cargo]}', '#{atestado[:data_admissao]}', '#{atestado[:produto]}', '#{atestado[:campanha]}', '#{atestado[:centro_custo]}', '#{atestado[:medico]}', '#{atestado[:crm]}', '#{DateTime.now.to_s}', '#{DateTime.now.to_s}')"
        # }
        #
        # values = inserts.join(' ,')
        #
        # sql = "INSERT INTO 'atestado_medicos' ( 'filial', 'matricula', 'login', 'nome', 'tipo', 'cid', 'descricao', 'data_entrega', 'data_atestado', 'qtd_dias', 'data_retorno', 'incluido', 'data_cadastro', 'gerente', 'veracidade', 'cargo', 'data_admissao', 'produto', 'campanha', 'centro_custo', 'medico', 'crm', 'created_at', 'updated_at') VALUES #{values}"


        ActiveRecord::Base.transaction {
          @legal_faults_not_registered.each{ |atestado|

            values = "(#{atestado[:filial]}, '#{atestado[:matricula]}', '#{atestado[:login]}', '#{atestado[:nome]}', '#{atestado[:tipo]}', '#{atestado[:cid]}', '#{atestado[:descricao]}', '#{atestado[:data_entrega]}', '#{atestado[:data_atestado]}', #{atestado[:qtd_dias]}, '#{atestado[:qtd_horas]}', '#{atestado[:data_retorno]}', '#{atestado[:incluido]}', '#{atestado[:data_cadastro]}', '#{atestado[:gerente]}', '#{atestado[:veracidade]}', '#{atestado[:cargo]}', '#{atestado[:data_admissao]}', '#{atestado[:produto]}', '#{atestado[:campanha]}', '#{atestado[:centro_custo]}', '#{atestado[:medico]}', '#{atestado[:crm]}', '#{DateTime.now.to_s}', '#{DateTime.now.to_s}')"

            ActiveRecord::Base.connection.execute "INSERT INTO atestado_medicos ( filial, matricula, login, nome, tipo, cid, descricao, data_entrega, data_atestado, qtd_dias, qtd_horas, data_retorno, incluido, data_cadastro, gerente, veracidade, cargo, data_admissao, produto, campanha, centro_custo, medico, crm, created_at, updated_at) VALUES #{values}"
          }
        }

        @total_inserted = @legal_faults_not_registered.count
#        end

        @benchmark[:finish] = Time.now
      else
        flash[:alert] = "Por favor, envie um arquivo do tipo Excel"
      end
    end
  end

  def relatorio_cids
    @matriculas = AtestadoMedico.distinct.order(:matricula).pluck(:matricula)
    @matriculas << 'Todas'
    @matricula = 'Todas'

    if params[:daterange].present?

      @matricula = params[:matricula]
      @qtd_ranking = params[:qtd_ranking]

      matricula_query = ''
      @daterange = params[:daterange]
      periodo = params[:daterange].split(' - ')

      @from = DateTime.parse(periodo[0]).strftime('%Y-%m-%d')
      @to = DateTime.parse(periodo[1]).strftime('%Y-%m-%d')

      if params[:matricula].present?
        if params[:matricula] != 'Todas'
          matricula_query = params[:matricula]
        end
      end

      if !matricula_query.blank?
        @atestados = AtestadoMedico.where(data_atestado: @from..@to, matricula: matricula_query).where.not(cid: '').order(data_atestado: :asc)
      else
        @atestados = AtestadoMedico.where(data_atestado: @from..@to).where.not(cid: '').order(data_atestado: :asc)
      end

      # http://blog.remarkablelabs.com/2012/12/not-equal-support-for-active-record-queries-rails-4-countdown-to-2013
    end
  end

end

app/views/seguranca_trabalho/_form.html.erb
<div class="col-md-12 ">
		<div class="panel panel-default">
			<div class="panel-heading">    <h3 class="panel-title">Informe o período para busca</h3></div>
			<div class="panel-body">
				<%= form_tag(path, action: 'upload', class: '') do %>
					<div class="col-md-3">
						<div class="form-group">
							<label>Período</label>
							<%= text_field_tag :daterange, @daterange, required: true, class:"form-control" %>
						</div>
					</div>
						<%= hidden_field_tag :commit, value: 'true' %>
					<div class="col-md-12">
						<%= button_tag(type: 'submit', class: "btn btn-primary") do %>
							<i class="glyphicon glyphicon-search"></i> Buscar
						<% end %>
					</div>
				<% end %>
				</div>
		</div>
</div>
<script type="text/javascript">

$(document).ready(function(){

	$('input[name="daterange"]').daterangepicker({
		locale: {
      format: 'DD/MM/YYYY',
			separator: ' - ',
      applyLabel: 'Aplicar',
      cancelLabel: 'Limpar',
      fromLabel: 'De',
      toLabel: 'Para',
      customRangeLabel: 'Personalizado'
    },
		ranges: {
           'Hoje': [moment(), moment()],
           'Ontem': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
           'Últimos 7 Dias': [moment().subtract(6, 'days'), moment()],
           'Últimos 30 Dias': [moment().subtract(29, 'days'), moment()],
           'Este Mês': [moment().startOf('month'), moment().endOf('month')],
           'Último Mês': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        }
	});


});

</script>

app/views/seguranca_trabalho/faltas_legais_old.html.erb
<%= render partial: 'form_old', locals: { path: seguranca_trabalho_faltas_legais_old_path } %>
<div class="col-md-12 ">
		<% if @benchmark %>
			<small><%= (@benchmark[:finish] - @benchmark[:start])*1000 %> miliseg</small>
		<% end %>
	<div id="container-dashboard" class="col-md-12 ">

	</div>
	<div id="container-period" class="col-md-12 ">

	</div>


	<ul class="nav nav-tabs" role="tablist">
	    <li role="presentation" class="active"><a href="#panel-1" aria-controls="panel-1" role="tab" data-toggle="tab">Detalhes</a></li>
	    <li role="presentation"><a href="#panel-2" aria-controls="panel-2" role="tab" data-toggle="tab">Grupos x Atestado</a></li>
	  </ul>

	  <!-- Tab panes -->
	  <div class="tab-content">
			<section role="tabpanel" class="tab-pane active" id="panel-1">
				<div id="container-enrollment" class="table-dashboard col-md-6 ">

				</div>
				<div id="container-legal-faults" class="table-dashboard col-md-6 ">

				</div>
				<div id="container-crm" class="table-dashboard col-md-12 ">

				</div>
				<div id="container-cid" class="col-md-12 ">

				</div>
			</section>
			<section role="tabpanel" class="tab-pane content-groups" id="panel-2">

			</section>
	    <div role="tabpanel" class="tab-pane active" id="home">...</div>
	    <div role="tabpanel" class="tab-pane" id="profile">...</div>
	    <div role="tabpanel" class="tab-pane" id="messages">...</div>
	    <div role="tabpanel" class="tab-pane" id="settings">...</div>
	  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
	var result = {
		'legalFaults': <%= raw @legal_faults.to_json %>
	}

	console.log(result);
	if (result['legalFaults']){
		LegalFaultsOld.feed(result['legalFaults']);
		LegalFaultsOld.init();
  }
});
</script>

app/views/seguranca_trabalho/importar.html.erb
<div class="col-md-12 ">
  <div class="panel panel-default">
    <div class="panel-heading">    <h3 class="panel-title">Envie a planilha para importação dos dados</h3></div>
    <div class="panel-body">
  <%= form_tag(seguranca_trabalho_importar_path, action: 'upload', multipart: true, class: 'form-inline') do %>
  <div class="form-group">
    <label>Arquivo no formato Excel (xls/xlsx) </label>
    <%= file_field_tag :file, value: @file, accept: 'application/vnd.ms-excel, application/msexcel, application/x-msexcel, application/x-ms-excel, application/vnd.ms-excel, application/x-excel, application/x-dos_ms_excel, application/xls, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', required: true %>
    <% if @file %>
    <p><%= @file.original_filename %></p>
    <% end %>
  </div>
  <%= submit_tag 'Enviar', class: "btn btn-primary btn-expand radius" %>
  <% end %>
</div>
</div>
</div>
<% if @legal_faults %>
<div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading">Resumo</div>
    <div class="panel-body">
      <p>Total de registros: <%= @legal_faults.data.count %> </br>
        Duplicados: <%= @legal_faults.duplicate_records %> </br>
        Registros com erros: <%= @total_errors %> </br>
        <hr/>
        Registros cadastrados anteriormente: <%= @legal_faults_registered.count %> </br>
        <hr/>
        Salvos no banco de dados: <%= @total_inserted %> </br>
        <hr/>
        Planilha foi lida em: <%= (@legal_faults.benchmark[:finish] - @legal_faults.benchmark[:start])*1000 %> miliseg </br>
        Dados foram analisados ou salvos em: <%= (@benchmark[:finish] - @benchmark[:start])*1000 %> miliseg
      </p>
    </div>
  </div>
</div>

<div class="col-md-6 ">
  <div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Inseridos no banco de dados (<%= @total_inserted %>)</h3></div>
    <div class="panel-body">


  <% if @total_inserted > 0 %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Registro</th>
      </tr>
    </thead>
    <tbody>
      <% @legal_faults.data.each{ |a| %>
        <tr>
          <td>
            <%= "#{a[:filial]} #{a[:matricula]} #{a[:login]} #{a[:nome]} #{a[:tipo]} #{a[:cid]} #{a[:descricao]} #{a[:data_entrega]} #{a[:data_atestado]} #{a[:qtd_dias]} #{a[:qtd_horas]}"%>
          </td>
        </tr>
        <%  } %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>
</div>
  <div class="col-md-6 ">
    <div class="panel panel-default">
      <div class="panel-heading"><h3 class="panel-title">Já cadastrados anteriormente (<%= @legal_faults_registered.blank? ? '0' : @legal_faults_registered.count %>)</h3></div>
      <div class="panel-body">

    <% if @legal_faults_registered %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Registro</th>
        </tr>
      </thead>
      <tbody>
        <% @legal_faults_registered.each{ |a| %>
          <tr>
            <td>
              <%= "#{a[:filial]} #{a[:matricula]} #{a[:login]} #{a[:nome]} #{a[:tipo]} #{a[:cid]} #{a[:descricao]} #{a[:data_entrega]} #{a[:data_atestado]} #{a[:qtd_dias]} #{a[:qtd_horas]}"%>
            </td>
          </tr>
          <%  } %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/seguranca_trabalho/index.html.erb
<h1>SESMT</h1>

app/views/seguranca_trabalho/relatorio_abs.html.erb
<%= render partial: 'form_abs', locals: { path: seguranca_trabalho_relatorio_abs_path } %>
<% if @atestados_mensal_atestados %>
<div class="col-md-12 ">
	<div class="row">
		<div class="col-md-12 ">
			<div class="panel panel-default">
				<div class="panel-heading">ABS Mensal</div>
				<div class="panel-body">
					<div id="container-abs-monthly" class="col-md-12 ">

					</div>
					<div id="container-abs-monthly-area" class="col-md-12 ">

					</div>
					<div id="container-abs-monthly-total" class="col-md-6 ">

					</div>
					<div id="container-abs-monthly-total-percentage" class="col-md-6 ">

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var result = {
		absMensalAtestados: <%= raw @atestados_mensal_atestados ? @atestado.construir_abs_mensal(@atestados_mensal_atestados).to_json : '' %>,
		absMensalAtestadosArea: <%= raw @atestados_mensal_area ? @atestado.construir_abs_mensal_area(@atestados_mensal_area).to_json : '' %>,
		absMensalAtestadosTotalDias: <%= raw @atestados_mensal_total_dias ? @atestado.construir_abs_mensal_dias(@atestados_mensal_total_dias).to_json : '' %>,
	};

	 console.log(result);

	if (result.absMensalAtestados) {
		AtestadoMedicos.constructGraphAbsMonthly(result.absMensalAtestados);
		AtestadoMedicos.constructGraphAbsMonthlyArea(result.absMensalAtestadosArea);
		AtestadoMedicos.constructGraphAbsMonthlyTotalDays(result.absMensalAtestadosTotalDias);
		AtestadoMedicos.constructGraphAbsMonthlyTotalPercentage(result.absMensalAtestadosTotalDias);
	}
});
</script>
<% end %>

app/views/seguranca_trabalho/relatorio_atestados.html.erb
<%= render partial: 'form', locals: { path: seguranca_trabalho_relatorio_atestados_path } %>
<% if @atestados %>
<div class="col-md-12 ">
<div class="panel panel-default">
	<div class="panel-heading">Resumo <small>(tempo da busca: <%= ((@benchmark[:finish] - @benchmark[:start])*1000).round(3) %> miliseg)</small></div>
	<div class="panel-body">
		<div class="row">
			<div class="col-md-2 info-resumo">
				<p class="info-resumo__titulo">Atestados</p>
				<p class="info-resumo__numero"><%= @atestados.contagem_por_tipo(@atestados)[:atestado] %></p>
			</div>
			<div class="col-md-2">
				<p class="info-resumo__titulo">Declarações de horas</p>
				<p class="info-resumo__numero"><%= @atestados.contagem_por_tipo(@atestados)[:declaracao_de_horas] %></p>
			</div>
			<div class="col-md-2">
				<p class="info-resumo__titulo">Faltas legais</p>
				<p class="info-resumo__numero"><%= @atestados.contagem_por_tipo(@atestados)[:falta_legal] %></p>
			</div>
			<div class="col-md-2">
				<p class="info-resumo__titulo">Acompanhamentos</p>
				<p class="info-resumo__numero"><%= @atestados.contagem_por_tipo(@atestados)[:acompanhamento] %></p>
			</div>

			<div class="col-md-2">
				<p class="info-resumo__titulo">Certidões</p>
				<p class="info-resumo__numero"><%= @atestados.contagem_por_tipo(@atestados)[:certidao] %></p>
			</div>
			<div class="col-md-2">
				<p class="info-resumo__titulo">Total de pessoas</p>
				<p class="info-resumo__numero"><%= @atestados.contagem_por_matricula(@atestados)[:matriculas].count %></p>
			</div>
			<div class="col-md-2">
				<p class="info-resumo__titulo">Total de dias de atestados</p>
				<p class="info-resumo__numero" data-toggle="tooltip" data-placement="top" title="Aprox. <%= @atestados.contagem_por_matricula(@atestados)[:total_trabalhadores] %>  repres. - <%= @atestados.contagem_por_matricula(@atestados)[:total_meses] %> meses - <%= @atestados.contagem_por_matricula(@atestados)[:total_anos] %> anos">
					<%= @atestados.contagem_por_matricula(@atestados)[:total_dias] %>
				</p>
			</div>
		</div>

		<hr/>

		<div id="container-period" class="col-md-12 ">

		</div>
	</div>
</div>


	<ul class="nav nav-tabs " role="tablist">
		<li role="presentation" class="active"><a href="#panel-1" aria-controls="panel-1" role="tab" data-toggle="tab">Detalhes</a></li>
		<li role="presentation" id="tab2" ><a href="#panel-2" aria-controls="panel-2" role="tab" data-toggle="tab">Centro de Custo x Atestado - Atestados</a></li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<section role="tabpanel" class="tab-pane active" id="panel-1">
				<div class="row"> <!-- row -->

					<div class="col-md-12">
						<div class="panel panel-default">
							<div class="panel-heading">Matrícula (<%= @atestados.contagem_por_matricula(@atestados)[:matriculas].count %>)</div>
							<div class="panel-body">
								<table id="matricula" class="table table-striped">
									<thead>
										<tr>
											<th>Matrícula</th>
											<th>Atestados</th>
											<th>Dias</th>
											<th>Declarações</th>
											<th>Horas</th>
											<th>Faltas</th>
											<th>Acomp.</th>
											<th>Data admissão</th>
										</tr>
									</thead>
									<tfoot>
										<tr>
											<th>Matrícula</th>
											<th>Atestados</th>
											<th>Dias</th>
											<th>Declarações</th>
											<th>Horas</th>
											<th>Faltas</th>
											<th>Acomp.</th>
											<th>Data admissão</th>
										</tr>
									</tfoot>
									<tbody>
										<% @atestados.contagem_por_matricula(@atestados)[:matriculas].each{ |key, value| %>
											<tr>
												<td>
													<%= key %>
												</td>
												<td>
													<%= value[:atestado] %>
												</td>
												<td>
													<%= value[:dias] %>
												</td>
												<td>
													<%= value[:declaracao_de_horas] %>
												</td>
												<td>
													<%= value[:horas] %>
												</td>
												<td>
													<%= value[:falta_legal] %>
												</td>
												<td>
													<%= value[:acompanhamento] %>
												</td>
												<td>
													<%= value[:data_admissao].strftime("%d/%m/%Y") %>
												</td>
											</tr>
											<%  } %>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="panel panel-default">
							<div class="panel-heading">Faltas legais (<%= @atestados.contagem_por_tipo_atestado(@atestados,'falta legal').count %>)</div>
							<div class="panel-body">
								<table id="falta_legal" class="table table-striped">
									<thead>
										<tr>
											<th>Matrícula</th>
											<th>Descrição</th>
											<th>Dias</th>
										</tr>
									</thead>
									<tfoot>
										<tr>
											<th>Matrícula</th>
											<th>Descrição</th>
											<th>Dias</th>
										</tr>
									</tfoot>
									<tbody>
										<% @atestados.contagem_por_tipo_atestado(@atestados,'falta legal').each{ |value| %>
											<tr>
												<td>
													<%= value[:matricula] %>
												</td>
												<td>
													<%= value[:descricao] %>
												</td>
												<td>
													<%= value[:dias] %>
												</td>
											</tr>
											<%  } %>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div class="col-md-12">
						<div class="panel panel-default">
							<div class="panel-heading">CRM (<%= @atestados.contagem_por_crm(@atestados).count %>)</div>
							<div class="panel-body">
								<table id="crm" class="table table-striped">
									<thead>
										<tr>
											<th>CRM</th>
											<th>Atestados</th>
											<th>Dias</th>
											<th>Declarações</th>
											<th>Horas</th>
											<th>Faltas</th>
											<th>Acomp.</th>
										</tr>
									</thead>
									<tfoot>
										<tr>
											<th>CRM</th>
											<th>Atestados</th>
											<th>Dias</th>
											<th>Declarações</th>
											<th>Horas</th>
											<th>Faltas</th>
											<th>Acomp.</th>
										</tr>
									</tfoot>
									<tbody>
										<% @atestados.contagem_por_crm(@atestados).each{ |key, value| %>
											<tr>
												<td>
													<%= key %>
												</td>
												<td>
													<%= value[:atestado] %>
												</td>
												<td>
													<%= value[:dias] %>
												</td>
												<td>
													<%= value[:declaracao_de_horas] %>
												</td>
												<td>
													<%= value[:horas] %>
												</td>
												<td>
													<%= value[:falta_legal] %>
												</td>
												<td>
													<%= value[:acompanhamento] %>
												</td>
											</tr>
											<%  } %>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div id="container-cid" class="col-md-12">

					</div>
				</div> <!-- row -->

		</section>
		<section role="tabpanel" class="tab-pane content-groups" id="panel-2">

		</section>
	</div> <!-- tab-content -->
<% end %>
				<script type="text/javascript">
				$(document).ready(function() {
					var result = {
						atestadosDataAtestado: <%= raw @atestados ? @atestados.contagem_por_data_atestado(@atestados).to_json : '' %>,
						atestadosCidPorCentro: <%= raw @atestados ? @atestados.contagem_cid_por_centro_custo(@atestados).to_json: '' %>
					},
	        graphByPeriodConstructed = false;

					if (result.atestadosDataAtestado) {
						AtestadoMedicos.feed(result);
						AtestadoMedicos.init();

						$('#tab2').on('click',function(){
		          if(graphByPeriodConstructed == false) {
		            AtestadoMedicos.constructGraphByCostCenter(result.atestadosCidPorCentro);
		            graphByPeriodConstructed = true;
		          }
		        });
					}
				});
				</script>

app/views/seguranca_trabalho/relatorio_cids.html.erb
<%= render partial: 'form_cids', locals: { path: seguranca_trabalho_relatorio_cids_path } %>
<% if @atestados %>
<div class="col-md-12 ">
	<div class="row">
		<div class="col-md-12 ">
			<div class="panel panel-default">
				<div class="panel-heading">Frequência diária</div>
				<div class="panel-body">
					<div id="container-period-cid">

					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6 ">
			<div class="panel panel-default">
				<div class="panel-heading">Ranking</div>
				<div class="panel-body">
					<div id="container-cid">

					</div>
					<div id="container-legend-cid">

					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="panel panel-default">
				<div class="panel-heading">Registros (<%= @atestados.size %>)</div>
				<div class="panel-body">
					<table id="matricula-cid" class="table table-striped">
						<thead>
							<tr>
								<th>Matrícula</th>
								<th>CID</th>
								<th>Data do atestado</th>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<th>Matrícula</th>
								<th>CID</th>
								<th>Data do atestado</th>
							</tr>
						</tfoot>
						<tbody>
							<% @atestados.each{ |a| %>
								<tr>
									<td>
										<%= a[:matricula] %>
									</td>
									<td>
										<%= a[:cid] %>
									</td>
									<td>
										<%= a[:data_atestado].strftime("%d/%m/%Y") %>
									</td>
								</tr>
								<%  } %>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(document).ready(function() {
	var result = {
		cidDataAtestado: <%= raw @atestados ? @atestados.contagem_cid_por_data_atestado(@atestados).to_json : '' %>,
		cid: <%= raw @atestados ? @atestados.contagem_cid(@atestados).to_json : '' %>,

	};

	console.log(result);

	if (result.cidDataAtestado) {
		AtestadoMedicos.constructDataTableByCID();
		AtestadoMedicos.constructGraphByPeriodByCid(result.cidDataAtestado, 1, result.cid, <%= raw @qtd_ranking %>);
		AtestadoMedicos.constructGraphByCid(result.cid, 1, result.cid, <%= raw @qtd_ranking %>);

	}
});
</script>
<% end %>