config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  get 'seguranca_trabalho/index', to: 'seguranca_trabalho#index', path: 'sesmt'
  match 'seguranca_trabalho/importar', to: 'seguranca_trabalho#importar', path: 'importar', via: [:get, :post]

  get 'servico/index', to: 'servico#index', path: 'servico'

  match 'seguranca_trabalho/relatorio_atestados', to: 'seguranca_trabalho#relatorio_atestados', path: 'sesmt/relatorio_atestados', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_cids', to: 'seguranca_trabalho#relatorio_cids', path: 'sesmt/relatorio_cids', via: [:get, :post]
  match 'seguranca_trabalho/relatorio_abs', to: 'seguranca_trabalho#relatorio_abs', path: 'sesmt/relatorio_abs', via: [:get, :post]


  match 'seguranca_trabalho/faltas_legais_old', to: 'seguranca_trabalho#faltas_legais_old', path: 'sesmt/faltas_legais_old', via: [:get, :post]

  match 'servico/boleto', to: 'servico#boleto', path: 'servico/boleto', via: [:get, :post]

  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? content_for(:title) : "Gerenciador" %> - Vikstar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <img src="/images/logo-vikstar.png"/>
      </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     <ul class="nav navbar-nav">
       <li><%= link_to "Serviços", servico_index_path %></li>
       <li class="dropdown">
         <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SESMT<span class="caret"></span></a>
         <ul class="dropdown-menu">
           <li><%= link_to "Relatório dos Atestados", seguranca_trabalho_relatorio_atestados_path %></li>
           <li><%= link_to "Relatório de ABS", seguranca_trabalho_relatorio_abs_path %></li>
           <li><%= link_to "Relatório das CIDs", seguranca_trabalho_relatorio_cids_path %></li>
           <li role="separator" class="divider"></li>
           <li><%= link_to "Importação de dados", seguranca_trabalho_importar_path %></li>
         </ul>
       </li>
     </ul>
   </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |type, message| %>
    <div data-alert class="alert-box <%= type %> radius">
      <%= message %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      <%= yield %>
    </div>
  </div>
</div>
<link href="http://fonts.googleapis.com/css?family=Lato:400,700,900" rel="stylesheet" type="text/css">
</body>
</html>